### ISSUE TITLE
Wave Removes StartupProbes

### ISSUE THREAD

**Issue by jan-kantert** [wave-k8s/wave#137] opened 2024-01-09 09:22 UTC
If you add a `startupProbe` to any deployment/pod with a wave annotation that will be removed by wave. This is probably caused by an old version of the kubernetes API used in wave.

**Comment by starkers** [comment] 2024-02-01 15:38
Yes; I think you are right

**Comment by toelke** [comment] 2024-02-12 07:21
This is an understandable duplicate of #118

**Comment by jan-kantert** [comment] 2024-04-17 16:35
Will be fixed by #145

**Comment by toelke** [comment] 2024-04-26 09:18
Fixed with #145

**Closed by toelke** 2024-04-26 09:18 UTC
Labels: bug, duplicate
